/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0-beta.9.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface VastuRemedy {
    userName: string;
    numerologyNumber: bigint;
    preferredDirections: Array<string>;
    vastuSuggestions: Array<string>;
    remedyInstructions: string;
}
export interface NumerologyReport {
    userName: string;
    birthDate: string;
    favorableColors: Array<string>;
    relationshipGuidance: string;
    lifePathNumber: bigint;
    careerRecommendations: Array<string>;
    luckyNumbers: Array<bigint>;
    birthChartAnalysis: string;
}
export interface AvailableSlot {
    isAvailable: boolean;
    slotId: bigint;
    timeRange: string;
    timestamp: bigint;
}
export interface ConsultationBooking {
    userName: string;
    bookingId: bigint;
    bookingStatus: string;
    contactNumber: string;
    selectedTimeSlot: string;
}
export interface backendInterface {
    addAvailableSlot(timeRange: string): Promise<AvailableSlot>;
    bookConsultation(userName: string, contactNumber: string, selectedTimeSlot: string): Promise<ConsultationBooking>;
    generateNumerologyReport(userName: string, birthDate: string): Promise<NumerologyReport>;
    getAllBookings(): Promise<Array<ConsultationBooking>>;
    getAllNumerologyReports(): Promise<Array<NumerologyReport>>;
    getAllVastuRemedies(): Promise<Array<VastuRemedy>>;
    getAvailableTimeSlots(): Promise<Array<AvailableSlot>>;
    getVastuRemedies(userName: string, numerologyNumber: bigint): Promise<VastuRemedy>;
}
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addAvailableSlot(arg0: string): Promise<AvailableSlot> {
        if (this.processError) {
            try {
                const result = await this.actor.addAvailableSlot(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addAvailableSlot(arg0);
            return result;
        }
    }
    async bookConsultation(arg0: string, arg1: string, arg2: string): Promise<ConsultationBooking> {
        if (this.processError) {
            try {
                const result = await this.actor.bookConsultation(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.bookConsultation(arg0, arg1, arg2);
            return result;
        }
    }
    async generateNumerologyReport(arg0: string, arg1: string): Promise<NumerologyReport> {
        if (this.processError) {
            try {
                const result = await this.actor.generateNumerologyReport(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.generateNumerologyReport(arg0, arg1);
            return result;
        }
    }
    async getAllBookings(): Promise<Array<ConsultationBooking>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllBookings();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllBookings();
            return result;
        }
    }
    async getAllNumerologyReports(): Promise<Array<NumerologyReport>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllNumerologyReports();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllNumerologyReports();
            return result;
        }
    }
    async getAllVastuRemedies(): Promise<Array<VastuRemedy>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllVastuRemedies();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllVastuRemedies();
            return result;
        }
    }
    async getAvailableTimeSlots(): Promise<Array<AvailableSlot>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAvailableTimeSlots();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAvailableTimeSlots();
            return result;
        }
    }
    async getVastuRemedies(arg0: string, arg1: bigint): Promise<VastuRemedy> {
        if (this.processError) {
            try {
                const result = await this.actor.getVastuRemedies(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVastuRemedies(arg0, arg1);
            return result;
        }
    }
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, uploadFile, downloadFile, options.processError);
}
