/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0-beta.9.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AvailableSlot {
  'isAvailable' : boolean,
  'slotId' : bigint,
  'timeRange' : string,
  'timestamp' : bigint,
}
export interface ConsultationBooking {
  'userName' : string,
  'bookingId' : bigint,
  'bookingStatus' : string,
  'contactNumber' : string,
  'selectedTimeSlot' : string,
}
export interface NumerologyReport {
  'userName' : string,
  'birthDate' : string,
  'favorableColors' : Array<string>,
  'relationshipGuidance' : string,
  'lifePathNumber' : bigint,
  'careerRecommendations' : Array<string>,
  'luckyNumbers' : Array<bigint>,
  'birthChartAnalysis' : string,
}
export interface VastuRemedy {
  'userName' : string,
  'numerologyNumber' : bigint,
  'preferredDirections' : Array<string>,
  'vastuSuggestions' : Array<string>,
  'remedyInstructions' : string,
}
export interface _SERVICE {
  'addAvailableSlot' : ActorMethod<[string], AvailableSlot>,
  'bookConsultation' : ActorMethod<
    [string, string, string],
    ConsultationBooking
  >,
  'generateNumerologyReport' : ActorMethod<[string, string], NumerologyReport>,
  'getAllBookings' : ActorMethod<[], Array<ConsultationBooking>>,
  'getAllNumerologyReports' : ActorMethod<[], Array<NumerologyReport>>,
  'getAllVastuRemedies' : ActorMethod<[], Array<VastuRemedy>>,
  'getAvailableTimeSlots' : ActorMethod<[], Array<AvailableSlot>>,
  'getVastuRemedies' : ActorMethod<[string, bigint], VastuRemedy>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];