/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0-beta.9.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const AvailableSlot = IDL.Record({
  'isAvailable' : IDL.Bool,
  'slotId' : IDL.Nat,
  'timeRange' : IDL.Text,
  'timestamp' : IDL.Int,
});
export const ConsultationBooking = IDL.Record({
  'userName' : IDL.Text,
  'bookingId' : IDL.Nat,
  'bookingStatus' : IDL.Text,
  'contactNumber' : IDL.Text,
  'selectedTimeSlot' : IDL.Text,
});
export const NumerologyReport = IDL.Record({
  'userName' : IDL.Text,
  'birthDate' : IDL.Text,
  'favorableColors' : IDL.Vec(IDL.Text),
  'relationshipGuidance' : IDL.Text,
  'lifePathNumber' : IDL.Nat,
  'careerRecommendations' : IDL.Vec(IDL.Text),
  'luckyNumbers' : IDL.Vec(IDL.Nat),
  'birthChartAnalysis' : IDL.Text,
});
export const VastuRemedy = IDL.Record({
  'userName' : IDL.Text,
  'numerologyNumber' : IDL.Nat,
  'preferredDirections' : IDL.Vec(IDL.Text),
  'vastuSuggestions' : IDL.Vec(IDL.Text),
  'remedyInstructions' : IDL.Text,
});

export const idlService = IDL.Service({
  'addAvailableSlot' : IDL.Func([IDL.Text], [AvailableSlot], []),
  'bookConsultation' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [ConsultationBooking],
      [],
    ),
  'generateNumerologyReport' : IDL.Func(
      [IDL.Text, IDL.Text],
      [NumerologyReport],
      [],
    ),
  'getAllBookings' : IDL.Func([], [IDL.Vec(ConsultationBooking)], ['query']),
  'getAllNumerologyReports' : IDL.Func(
      [],
      [IDL.Vec(NumerologyReport)],
      ['query'],
    ),
  'getAllVastuRemedies' : IDL.Func([], [IDL.Vec(VastuRemedy)], ['query']),
  'getAvailableTimeSlots' : IDL.Func([], [IDL.Vec(AvailableSlot)], ['query']),
  'getVastuRemedies' : IDL.Func([IDL.Text, IDL.Nat], [VastuRemedy], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const AvailableSlot = IDL.Record({
    'isAvailable' : IDL.Bool,
    'slotId' : IDL.Nat,
    'timeRange' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  const ConsultationBooking = IDL.Record({
    'userName' : IDL.Text,
    'bookingId' : IDL.Nat,
    'bookingStatus' : IDL.Text,
    'contactNumber' : IDL.Text,
    'selectedTimeSlot' : IDL.Text,
  });
  const NumerologyReport = IDL.Record({
    'userName' : IDL.Text,
    'birthDate' : IDL.Text,
    'favorableColors' : IDL.Vec(IDL.Text),
    'relationshipGuidance' : IDL.Text,
    'lifePathNumber' : IDL.Nat,
    'careerRecommendations' : IDL.Vec(IDL.Text),
    'luckyNumbers' : IDL.Vec(IDL.Nat),
    'birthChartAnalysis' : IDL.Text,
  });
  const VastuRemedy = IDL.Record({
    'userName' : IDL.Text,
    'numerologyNumber' : IDL.Nat,
    'preferredDirections' : IDL.Vec(IDL.Text),
    'vastuSuggestions' : IDL.Vec(IDL.Text),
    'remedyInstructions' : IDL.Text,
  });
  
  return IDL.Service({
    'addAvailableSlot' : IDL.Func([IDL.Text], [AvailableSlot], []),
    'bookConsultation' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [ConsultationBooking],
        [],
      ),
    'generateNumerologyReport' : IDL.Func(
        [IDL.Text, IDL.Text],
        [NumerologyReport],
        [],
      ),
    'getAllBookings' : IDL.Func([], [IDL.Vec(ConsultationBooking)], ['query']),
    'getAllNumerologyReports' : IDL.Func(
        [],
        [IDL.Vec(NumerologyReport)],
        ['query'],
      ),
    'getAllVastuRemedies' : IDL.Func([], [IDL.Vec(VastuRemedy)], ['query']),
    'getAvailableTimeSlots' : IDL.Func([], [IDL.Vec(AvailableSlot)], ['query']),
    'getVastuRemedies' : IDL.Func([IDL.Text, IDL.Nat], [VastuRemedy], []),
  });
};

export const init = ({ IDL }) => { return []; };